# Generated by Django 4.0.4 on 2022-06-15 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ordered', 'ordered'), ('pending', 'pending'), ('delivered', 'delivered')], default='ordered', max_length=30),
        ),
    ]
