# Generated by Django 4.0.4 on 2022-06-19 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_items_orderitems_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
