# Generated by Django 4.0.4 on 2022-06-28 13:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_order_total_amount_alter_orderitems_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitems',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='order',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
