# Generated by Django 4.0.4 on 2022-07-03 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_is_driver_user_is_student'),
        ('api', '0008_delete_delivery_delete_driver'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('address', models.CharField(max_length=100)),
                ('vehicle_type', models.CharField(max_length=20)),
                ('driver_license', models.CharField(max_length=20)),
            ],
        ),
    ]
