# Generated by Django 4.0.4 on 2022-07-07 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_delivery'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Delivery',
        ),
    ]
