# Generated by Django 4.0.4 on 2022-07-08 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_delivery'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Delivery',
        ),
    ]
