# Generated by Django 4.0.4 on 2022-07-03 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_is_driver_user_is_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_student',
            new_name='is_customer',
        ),
    ]
